### DISCUSSION TITLE
Import of external compose projects issue

### DISCUSSION THREAD

**Discussion by bearded-papa** [getarcaneapp/arcane#318] [Q&A]
I have added the bind mount to my external compose files as instructed 
```
- /mnt/media/docker/compose:/mnt/media/docker/compose:ro
```
FULL COMPOSE
```
services:
  arcane:
    image: ghcr.io/ofkm/arcane:latest
    container_name: arcane
    ports:
      - 3981:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/media/docker/arcane/arcane-data:/app/data
      - /mnt/media/docker/compose:/mnt/media/docker/compose:ro
    environment:
      - APP_ENV=production # Required
      - PUBLIC_SESSION_SECRET=<SECRET> # Generate: openssl rand -base64 32
      # Optional: Match your host user for permissions
      - PUID=1001
      - PGID=1001
      # Optional: Set if Docker access fails
      # - DOCKER_GID=998
      # Optional: For local HTTP testing only
      # - PUBLIC_ALLOW_INSECURE_COOKIES=true
    restart: unless-stopped
    networks:
      - frontend
networks:
  frontend:
    external: true
```
But when I import and look at the compose it has imported is looks like this 
```
# Generated compose file for imported stack: filebrowser
# This was automatically generated by Arcane from an external stack.
# The original compose file could not be read from: /mnt/media/docker/filebrowser/compose.yaml.
# You may need to adjust this manually for correct operation.

services:
filebrowser:
    image: filebrowser/filebrowser:v2.32.0
```
with the comment at the top saying it tried to import from
```
/mnt/media/docker/filebrowser/compose.yaml
```
Why is it ignoring the last part of the bind mount?
